#!/usr/bin/python
import argparse 
import time 
import serial 
import sys


class MicroKit():
	def __init__(self):
		#setup serial port 
		self.ser = serial.Serial(
			port=port,
			timeout=0.1
		)
    
    def WriteCommand(self,command=[]):
        
        ret = [] 

        #write command packet
        self.ser.write(command)
        
        #wait for ack response, 16 bytes long 
        ret = self.ser.read(16)

        return ret
        
	

def main(self):
    #start of main program 
    #argument parsing 
    parser = argparse.ArgumentParser(description='Hex Programmer Utility')
    parser.add_argument('-s','--serial', help='Serial Port Device File', required=True)


    logfile = None 
    args         = vars(parser.parse_args())
    port         = args['serial']



      	
      
      
